"""initial schema: job and scaling_event tables

Creates the two durable tables (TDD §5.7) and their time/state indexes. Hand-written (not
autogenerated) so the column types and nullability match the spec exactly.

Revision ID: 0001
Revises:
Create Date: 2026-06-03
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("guest_handle", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("complexity", sa.SmallInteger(), nullable=False),
        sa.Column("max_retries", sa.SmallInteger(), nullable=False),
        sa.Column("retry_delay_ms", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_submitted_at", "job", ["submitted_at"])
    op.create_index("ix_job_state", "job", ["state"])

    op.create_table(
        "scaling_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("worker_count_after", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_scaling_event_at", "scaling_event", ["at"])


def downgrade() -> None:
    op.drop_index("ix_scaling_event_at", table_name="scaling_event")
    op.drop_table("scaling_event")
    op.drop_index("ix_job_state", table_name="job")
    op.drop_index("ix_job_submitted_at", table_name="job")
    op.drop_table("job")
